name: build-mpy

on: workflow_dispatch

jobs:
  setup-mpy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Versions
        run: |
          python3 --version
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          filter: 'blob:none'
          fetch-depth: 0
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0
          sudo apt-get install -y gettext
          pip install mpy-cross
      - name: Display mpy help
        run: |
          mpy-cross --version
        
  run-and-upload:
    name: Run mpy on ducky
    runs-on: ubuntu-latest
    needs: setup-mpy
    steps:
      - name: mpy ducky
        run: |
          mpy-cross ducky.py
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: ducky-mpy
          path: ducky.mpy
    
  now-download:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: run-and-upload
    steps:
      - name: Download single artifact
        uses: actions/download-artifact@v4
        with:
          name: ducky-mpy
